version: '3.9'

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: password
  MYSQL_DATABASE: sampledb

services:
  mysql-db:
    image: mysql:5
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: mypass123
    ports:
      - 3306:3306
  mysql-db-test:
    image: mysql:5
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: mypass123
    ports:
      - 3307:3306
